name: Crypto Fundraising Monitor

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 UTC 00:00 (한국시간 09:00)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_crypto_fundraising.txt
    
    - name: Run Crypto Fundraising Monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        HIGHLIGHT_THRESHOLD: ${{ secrets.HIGHLIGHT_THRESHOLD || '7' }}
        RUN_TIMEZONE: ${{ secrets.RUN_TIMEZONE || 'Asia/Seoul' }}
      run: |
        python crypto_fundraising_monitor/run.py
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: crypto-fundraising-logs
        path: |
          crypto_fundraising_monitor.log
          crypto_fundraising_state.db 